preset: psr2

risky: true

enabled:
  - alpha_ordered_imports
  - array_indentation
  - binary_operator_spaces
  - combine_consecutive_issets
  - combine_consecutive_unsets
  - comment_to_phpdoc
  - compact_nullable_typehint
  - concat_with_spaces
  - fully_qualified_strict_types
  - function_typehint_space
  - hash_to_slash_comment
  - include
  - is_null
  - linebreak_after_opening_tag
  - lowercase_cast
  - magic_constant_casing
  - method_chaining_indentation
  - method_separation
  - modernize_types_casting
  - multiline_comment_opening_closing
  - native_function_casing
  - newline_before_semicolons_chained
  - no_alias_functions
  - no_alternative_syntax
  - no_blank_lines_after_class_opening
  - no_blank_lines_after_phpdoc
  - no_blank_lines_after_return
  - no_blank_lines_after_throw
  - no_blank_lines_before_namespace
  - no_blank_lines_between_imports
  - no_empty_comment
  - no_empty_phpdoc
  - no_empty_statement
  - no_extra_block_blank_lines
  - no_homoglyph_names
  - no_leading_import_slash
  - no_leading_namespace_whitespace
  - no_multiline_whitespace_around_double_arrow
  - no_null_property_initialization
  - no_php4_constructor
  - no_short_bool_cast
  - no_singleline_whitespace_before_semicolons
  - no_spaces_inside_offset
  - no_spaces_outside_offset
  - no_superfluous_elseif
  - no_trailing_comma_in_singleline_array
  - no_unneeded_curly_braces
  - no_unneeded_final_method
  - no_unused_imports
  - no_useless_else
  - no_useless_return
  - no_whitespace_before_comma_in_array
  - no_whitespace_in_blank_line
  - non_printable_character
  - normalize_index_brace
  - object_operator_without_whitespace
  - phpdoc_add_missing_param_annotation
  - phpdoc_annotation_without_dot
  - phpdoc_indent
  - phpdoc_no_access
  - phpdoc_no_package
  - phpdoc_no_useless_inheritdoc
  - phpdoc_return_self_reference
  - phpdoc_scalar
  - phpdoc_single_line_var_spacing
  - phpdoc_trim
  - phpdoc_type_to_var
  - phpdoc_types
  - post_increment
  - print_to_echo
  - property_separation
  - self_accessor
  - semicolon_after_instruction
  - short_array_syntax
  - short_list_syntax
  - short_scalar_cast
  - simplified_null_return
  - single_quote
  - space_after_semicolon
  - standardize_increment
  - standardize_not_equals
  - strict_comparison
  - ternary_operator_spaces
  - ternary_to_null_coalescing
  - trailing_comma_in_multiline_array
  - trim_array_spaces
  - unalign_double_arrow
  - unalign_equals
  - unary_operator_spaces
  - whitespace_after_comma_in_array
